name: "Puppet"
description: "Turn dashboards into nice pictures"
version: "1.19.0"
slug: "puppet"
homeassistant_api: true
init: false
arch:
  - aarch64
  - amd64
ports:
  10000/tcp: 10000
options:
  access_token: ""
  home_assistant_url: ""
  keep_browser_open: false
  dashboard_urls:
    - url: ""
      refersh_after_min: 60 
schema:
  access_token: str
  home_assistant_url: str
  keep_browser_open: bool
  dashboard_urls:
    - url: str
      refersh_after_min: int 
